# inspired from https://github.com/BretFisher/node-docker-good-defaults
version: '3.1'

services:
  node:
    build:
      context: .
    command: ./node_modules/.bin/nodemon
    ports:
      - "3000:3000"
      - "9229:9229" # for debug purpose
    volumes:
      # bind mount host directory in container
      - .:/app:delegated
      # let you add packages during development without rebuilding
      # docker-compose exec node npm install --save <package name>
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      # this is a workaround to prevent host node_modules from accidently getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /opt/node_modules location.
      - notused:/app/node_modules

volumes:
  notused:

